### ISSUE TITLE
Build fails at setting up Casper Scripts

### ISSUE THREAD

**Issue by dkowis** [pop-os/pop-arm64#9]
```
[info] Synchronizing changes to disk
[info] Setting up casper scripts
sed: can't read /usr/share/initramfs-tools/scripts/casper-bottom/52gnome_initial_setup: No such file or directory
Container pop-os failed with error code 2.
```

Logging before I look into it.

**Comment by dkowis** [comment]
I think that might be a red herring. Earlier error included:

```
[install live utilities] /etc/apt/sources.list.d/pop-os-apps.sources:URIs: http://apt.pop-os.org/proprietary
[install live utilities] Traceback (most recent call last):
[install live utilities] File "/usr/lib/python3/dist-packages/repolib/shortcuts/ppa.py", line 32, in <module>
[install live utilities] from launchpadlib.launchpad import Launchpad
[install live utilities] ModuleNotFoundError: No module named 'launchpadlib'
[install live utilities]
[install live utilities] During handling of the above exception, another exception occurred:
[install live utilities]
[install live utilities] Traceback (most recent call last):
[install live utilities] File "/usr/bin/apt-manage", line 31, in <module>                                                                           [install live utilities] import repolib
[install live utilities] File "/usr/lib/python3/dist-packages/repolib/__init__.py", line 34, in <module>
[install live utilities] from .shortcuts import PPASource, PopdevSource, shortcut_prefixes
[install live utilities] File "/usr/lib/python3/dist-packages/repolib/shortcuts/__init__.py", line 24, in <module>
[install live utilities] from .ppa import PPASource
[install live utilities] File "/usr/lib/python3/dist-packages/repolib/shortcuts/ppa.py", line 35, in <module>
[install live utilities] raise SourceError(
[install live utilities] repolib.source.SourceError: Missing optional dependency "launchpadlib". Try `sudo apt install python3-launchpadlib` to inst
```

So I think that python3-launchpadlib needs to be added to the live utilities section. Also interesting to note that it doesn't fail the build when that fails....

**Comment by dkowis** [comment]
Okay, adding `python3-launchpadlib` to the initial buildroot gets me further, but casper is super upset:
```
[install live utilities] Reading package lists...
[install live utilities] Building dependency tree...
[install live utilities] You might want to run 'apt --fix-broken install' to correct these.
[install live utilities] The following packages have unmet dependencies:
[install live utilities] casper : Depends: libplymouth5 (>= 0.9.2) but it is not going to be installed
[install live utilities] Depends: user-setup but it is not going to be installed
[install live utilities] Depends: uuid-runtime but it is not going to be installed
[install live utilities] Depends: localechooser-data (>= 2.65ubuntu1) but it is not going to be installed or
[install live utilities] ubiquity but it is not going to be installed
[install live utilities] Depends: file but it is not going to be installed
[install live utilities] Depends: lzma
[install live utilities] Depends: cifs-utils but it is not going to be installed
[install live utilities] Depends: finalrd but it is not going to be installed
[install live utilities] Depends: fdisk but it is not going to be installed
[install live utilities] distinst : Depends: libdistinst (= 0.3.2~1663157572~22.04~d343ec3) but it is not going to be installed
[install live utilities] Depends: libparted-fs-resize0 (>= 3.1) but it is not going to be installed
[install live utilities] Depends: libparted2 (>= 3.1) but it is not going to be installed
[install live utilities] expect : Depends: tcl8.6 but it is not going to be installed
[install live utilities] Depends: libtcl8.6 (>= 8.6.0) but it is not going to be installed
[install live utilities] Depends: tcl-expect but it is not going to be installed
[install live utilities] gparted : Depends: libatkmm-1.6-1v5 (>= 2.28.2) but it is not going to be installed
[install live utilities] Depends: libcairomm-1.0-1v5 (>= 1.12.0) but it is not going to be installed
[install live utilities] Depends: libglibmm-2.4-1v5 (>= 2.66.2) but it is not going to be installed
[install live utilities] Depends: libgtk-3-0 (>= 3.21.4) but it is not going to be installed
[install live utilities] Depends: libgtkmm-3.0-1v5 (>= 3.24.5) but it is not going to be installed
[install live utilities] Depends: libpangomm-1.4-1v5 (>= 2.46.1) but it is not going to be installed
[install live utilities] Depends: libparted-fs-resize0 (>= 3.1) but it is not going to be installed
[install live utilities] Depends: libparted2 (>= 3.1) but it is not going to be installed
[install live utilities] Depends: libsigc++-2.0-0v5 (>= 2.8.0) but it is not going to be installed
[install live utilities] Depends: gparted-common (= 1.3.1-1ubuntu1) but it is not going to be installed
[install live utilities] Depends: policykit-1 but it is not going to be installed
[install live utilities] pop-installer : Depends: distinst-v2 but it is not going to be installed
[install live utilities] Depends: libcairo2 (>= 1.2.4) but it is not going to be installed
[install live utilities] Depends: libgdk-pixbuf-2.0-0 (>= 2.22.0) but it is not going to be installed
[install live utilities] Depends: libgee-0.8-2 (>= 0.20.0) but it is not going to be installed
[install live utilities] Depends: libgnomekbd8 (>= 3.6.0) but it is not going to be installed
[install live utilities] Depends: libgranite6 (>= 6.0.0) but it is not going to be installed
[install live utilities] Depends: libgtk-3-0 (>= 3.21.6) but it is not going to be installed
[install live utilities] Depends: libpangocairo-1.0-0 (>= 1.14.0) but it is not going to be installed
[install live utilities] Depends: libpwquality1 (>= 1.1.0) but it is not going to be installed
[install live utilities] Recommends: pop-installer-session but it is not going to be installed
[install live utilities] python3-cryptography : Depends: python3-cffi-backend-api-min (<= 9729)
[install live utilities] Depends: python3-cffi-backend-api-max (>= 9729)
[install live utilities] spice-vdagent : Depends: libasound2 (>= 1.0.22)
[install live utilities] Depends: libdrm2 (>= 2.4.3) but it is not going to be installed
[install live utilities] Depends: libgtk-3-0 (>= 3.22) but it is not going to be installed
[install live utilities] Depends: libpciaccess0 but it is not going to be installed
[install live utilities] Depends: libx11-6 but it is not going to be installed
[install live utilities] Depends: libxinerama1 (>= 2:1.1.4) but it is not going to be installed
[install live utilities] Depends: libxrandr2 (>= 2:1.2.99.2) but it is not going to be installed
[install live utilities] E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
[info] Setting up pool
```

Perhaps this means that the dependencies for casper need to be installed? Or only some of them?
